### ISSUE TITLE
getting 403 errors from github actions

### ISSUE THREAD

**Issue by derlin** [jihchi/mermaid.ink#212]
Hello there! I have this project https://github.com/derlin/docker-compose-viz-mermaid that is using mermaid.ink under the hood to generate PNGs and JPEGs. It works perfectly well, but when running tests from GitHub Actions I always get `403 Forbidden` errors (it is new, was working before). Did you change something (CloudFlare or something similar)  that is now blocking non-browser-based requests?

I understand if you do not want me to use mermaid.ink from code, but I believe docker-compose-viz-mermaid is a good advertisement for your project and doesn't try to abuse it in any way. I would appreciate it if you could help me on this.

Thanks again for this lovely project ✨

**Comment by jihchi** [comment]
Hi @derlin ,

I didn't change any configurations on CloudFlare lately, the 403 error seems odd to me.

Would you be able to print out the header of the response when the tests failed on Github Actions?

**Comment by derlin** [comment]
Well, It seems CloudFlare is blocking requests coming from Microsoft (and thus Github Actions). I tried on another test repository the following workflow:

```yaml
name: Mermaid Ink Test

on:
  push:
    branches:
      - mermaid-ink
jobs:
  lala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: pip install requests
      - run: |
          python - <<EOF 
          import requests
          r = requests.get("https://mermaid.ink/img/eyJjb2RlIjogIiUle2luaXQ6IHsndGhlbWUnOiAnZGVmYXVsdCd9fSUlXG5mbG93Y2hhcnQgVEJcbiAgd2ViXG5cbiIsICJtZXJtYWlkIjogeyJ0aGVtZSI6ICJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9")
          print(f"got status: {r.status_code}")
          print("headers:")
          print(r.headers)
          EOF
```

Here is the output:

```
got status: 403
headers:
{'Date': 'Sun, 23 Jul 2023 17:08:23 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Permissions-Policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'Referrer-Policy': 'same-origin', 'X-Frame-Options': 'SAMEORIGIN', 'cf-mitigated': 'challenge', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan [19](https://github.com/derlin/ci-test/actions/runs/5637652539/job/15270995928#step:5:20)70 00:00:01 GMT', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=oND38W3RkEQMHzLziM4ZDvPuE%2F4Uw9O0hAFRQwyk%2FOTKI9s%2FFIdQSAkGZezGQlPtUi0SWuUcDbtTw4%2BMRUwgn2OvGfwv8hKqyOcDGGRKxTwSZreCEytyr4vCtDHTpg%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '7eb5867019b22e5d-DFW', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'}
```
