### ISSUE TITLE
Question: how to run in "seccomp" mode in k8s?

### ISSUE THREAD

**Issue by maldworth** [jihchi/mermaid.ink#417]
This is more of a question, than an issue. What I want to do is run it as an internal service, only with internal ingress traffic (no external traffic). Then my other pods can hit it internally to generate the images.

**Comment by jihchi** [comment]
Hi @maldworth , have you tried [Jessie Frazelle's seccomp profile for Chrome](https://github.com/Zenika/alpine-chrome/blob/master/chrome.json)? 

Something like [this](https://github.com/jihchi/mermaid.ink?tab=readme-ov-file#with-seccomp):

```sh
wget https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
docker run --security-opt seccomp=$(pwd)/chrome.json ghcr.io/jihchi/mermaid.ink
```

**Comment by maldworth** [comment]
> Hi @maldworth , have you tried [Jessie Frazelle's seccomp profile for Chrome](https://github.com/Zenika/alpine-chrome/blob/master/chrome.json)? 
> 
> Something like [this](https://github.com/jihchi/mermaid.ink?tab=readme-ov-file#with-seccomp):
> 
> ```sh
> wget https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
> docker run --security-opt seccomp=$(pwd)/chrome.json ghcr.io/jihchi/mermaid.ink
> ```
> 
> 

How does one pass those docker flags in with k8s? That's what I don't know how do.

**Comment by jihchi** [comment]
I haven't tried this but according to the [Set the Seccomp Profile for a Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-seccomp-profile-for-a-container), it seems work like this:

1. Download the `chrome.json` and save it In the `<kubelet-root-dir>/seccomp`. 
2. Add `securityContext` to the manifest file:

```yaml
apiVersion: v1
kind: Pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: chrome.json
  containers:
  - name: mermaid-ink
    image: ghcr.io/jihchi/mermaid.ink
...
```
