### ISSUE TITLE
Crashes after several SVG generations in v12.2.0 (v12.1.1 is stable)

### ISSUE THREAD

**Issue by as000fm** [jihchi/mermaid.ink#543]
I'm encountering consistent crashes when using version `v12.2.0` of the Docker image `ghcr.io/jihchi/mermaid.ink`, specifically after generating a few Mermaid diagrams as SVG (typically 3–5 in a row).

After a few successful conversions, the service logs the following:

```
ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
[ERROR:dbus/bus.cc:408] Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[WARNING:sandbox/policy/linux/sandbox_linux.cc:415] InitializeSandbox() called with multiple threads in process gpu-process.
```

This problem **does not occur** in version `v12.1.1`, which remains stable under the same load and usage patterns.

I'm running the container via Docker Compose:

```yaml
services:
  mermaid-ink-server:
    image: ghcr.io/jihchi/mermaid.ink:v12.2.0
    cap_add:
      - SYS_ADMIN
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
```

The issue persists across reboots of the host and makes the latest version difficult to use.

- Proxmox 8.4.1 - Debian GNU/Linux 12 (bookworm)
- Docker version 28.1.1
- HP 800 G3 - Intel i7-6700T - 32Gb RAM
- Running on the server itself, not in a LCX or VM.

Please advise if further debug logs or test cases would be helpful.
